# Generated by Django 4.1.5 on 2023-01-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegistrationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("user_name", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("mobile", models.BigIntegerField(unique=True)),
                ("email", models.EmailField(max_length=100)),
            ],
        ),
    ]
